"use client"

import { useState, useEffect } from "react"
import { 
  Coins, TrendingUp, Clock, Users, ArrowUpRight, Calculator,
  ChevronDown, HelpCircle, Copy, CheckCircle2, ShieldCheck, Zap, Loader2
} from "lucide-react"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import { fetchRpc } from "@/lib/rpc"
import { cn } from "@/lib/utils"

interface ValidatorData {
  address: string
  pubkey: string
  stake: number
  status: string
}

const FAQS = [
  {
    q: "What is Lumina Staking?",
    a: "Lumina uses a Proof-of-Stake consensus protocol. By locking or 'delegating' your LUM tokens to a validator, you help secure the blockchain and earn a portion of the block rewards in return. Staking rewards are distributed automatically at the end of each epoch."
  },
  {
    q: "What is the unbonding period?",
    a: "When you unstake (undelegate) your LUM tokens, they do not become liquid immediately. They undergo a mandatory 7-day unbonding period. During this unbonding time, you do not earn any staking rewards, and your tokens cannot be transferred or sold."
  },
  {
    q: "How are validator commission fees calculated?",
    a: "Validators manage node infrastructure, backups, and security. In exchange for this service, they charge a commission fee on the rewards generated by your delegation. For example, if a validator has a 5% commission and your delegation earns 100 LUM in rewards, 5 LUM is kept by the validator, and 95 LUM is credited directly to you."
  },
  {
    q: "What are the risks of slashing?",
    a: "Staking is highly rewarding, but carries responsibility. If the validator you choose double-signs blocks or undergoes severe consensus downtime, a portion of their total stake (including delegated tokens) can be permanently 'slashed' (up to 1% for severe infractions). Choosing highly reputable validators minimizes this risk."
  }
]

export default function StakingPage() {
  const [validators, setValidators] = useState<ValidatorData[]>([])
  const [networkStats, setNetworkStats] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const [stakeAmount, setStakeAmount] = useState<number>(1000)
  const [copiedId, setCopiedId] = useState<string | null>(null)
  const [openFaq, setOpenFaq] = useState<number | null>(null)
  const [showStakingModal, setShowStakingModal] = useState(false)
  const [selectedVal, setSelectedVal] = useState<ValidatorData | null>(null)

  const APY = 12.5

  // Fetch data from RPC node
  useEffect(() => {
    const loadData = async () => {
      try {
        const [valRes, statsRes] = await Promise.all([
          fetchRpc("/network/validators"),
          fetchRpc("/network/stats"),
        ])

        if (valRes.ok) {
          const valData = await valRes.json()
          if (valData && Array.isArray(valData.validators)) {
            const parsed: ValidatorData[] = valData.validators
              .map((v: any) => ({
                address: v.address || "",
                pubkey: v.pubkey || "0x",
                stake: parseInt(v.stake || "0", 10),
                status: v.status || "Inactive",
              }))
              .filter((v: ValidatorData) => v.status === "Active")
              .sort((a: ValidatorData, b: ValidatorData) => b.stake - a.stake)
            setValidators(parsed)
          }
        }

        if (statsRes.ok) {
          const statsData = await statsRes.json()
          setNetworkStats(statsData)
        }
      } catch (err) {
        console.error("Failed to fetch data from RPC node:", err)
      } finally {
        setLoading(false)
      }
    }

    loadData()
    const timer = setInterval(loadData, 15000)
    return () => clearInterval(timer)
  }, [])

  const totalStaked = validators.reduce((sum, v) => sum + v.stake, 0)

  // Reward calculations
  const dailyReward = (stakeAmount * (APY / 100)) / 365
  const monthlyReward = (stakeAmount * (APY / 100)) / 12
  const yearlyReward = stakeAmount * (APY / 100)

  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text)
    setCopiedId(id)
    setTimeout(() => setCopiedId(null), 2000)
  }

  const formatNumber = (num: number, dec: number = 2) => {
    return new Intl.NumberFormat("en-US", { minimumFractionDigits: dec, maximumFractionDigits: dec }).format(num)
  }

  const formatStake = (raw: number) => {
    const lum = raw / 1e18
    if (lum >= 1_000_000) return `${(lum / 1_000_000).toFixed(2)}M`
    if (lum >= 1_000) return `${(lum / 1_000).toFixed(2)}K`
    return lum.toFixed(2)
  }

  const shortAddr = (addr: string) => {
    if (addr.length <= 20) return addr
    return `${addr.slice(0, 14)}...${addr.slice(-8)}`
  }

  const handleOpenStaking = (validator: ValidatorData) => {
    setSelectedVal(validator)
    setShowStakingModal(true)
  }

  return (
    <div className="min-h-screen bg-[#f6f6f6] text-[#1e293b] font-sans">
      <Navbar />

      {/* Hero Header */}
      <div className="animate-hero-bg relative pt-12 pb-16 overflow-hidden">
        <div className="absolute inset-0 opacity-[0.08]" style={{ backgroundImage: 'radial-gradient(#10b981 1px, transparent 1px)', backgroundSize: '24px 24px' }} />
        <div className="absolute -top-12 left-1/4 w-80 h-80 bg-emerald-500/10 rounded-full blur-3xl animate-pulse" />
        <div className="absolute bottom-0 right-1/4 w-72 h-72 bg-teal-500/10 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '2s' }} />

        <div className="max-w-[1400px] mx-auto px-4 relative z-10 text-center space-y-4">
          <div className="inline-flex items-center gap-2 bg-white/5 border border-white/10 rounded-full px-4 py-1.5 backdrop-blur-md">
            <Coins className="w-4 h-4 text-emerald-400" />
            <span className="text-[10px] font-black text-white uppercase tracking-[0.2em]">High Yield Staking & Delegation</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-black text-white tracking-tighter uppercase italic">
            Staking <span className="bg-gradient-to-r from-emerald-400 to-teal-400 bg-clip-text text-transparent">Overview</span>
          </h1>
          <p className="text-slate-400 max-w-2xl mx-auto font-medium text-sm">
            Lock your LUM tokens, secure consensus integrity, and earn up to <span className="text-emerald-400 font-bold">{APY}% APY</span> paid out in network rewards.
          </p>
        </div>
      </div>

      <main className="max-w-[1200px] mx-auto px-4 -mt-8 relative z-20 pb-20 space-y-8">
        
        {/* Network Metrics Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {[
            { label: "Staking APY", val: `${APY}%`, sub: "Dynamic block reward yield", icon: TrendingUp, color: "text-emerald-500" },
            { label: "Total Staked", val: `${formatStake(totalStaked)} LUM`, sub: `${validators.length} active validators`, icon: Coins, color: "text-blue-500" },
            { label: "Unbonding Period", val: "7 Days", sub: "Mandatory lock unbonding", icon: Clock, color: "text-amber-500" },
            { label: "Block Height", val: networkStats?.total_height ?? "—", sub: `Chain: ${networkStats?.chain_id ?? "—"}`, icon: Users, color: "text-purple-500" },
          ].map((m, i) => (
            <div key={i} className="bg-white p-5 rounded-xl border border-slate-200 shadow-sm hover:shadow-md transition-shadow">
              <div className="flex items-center justify-between mb-3">
                <div className={cn("p-2 rounded-lg bg-slate-50 border border-slate-100", m.color)}>
                  <m.icon className="w-5 h-5" />
                </div>
                <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{m.label}</span>
              </div>
              <div className="text-2xl font-black text-slate-900 tabular-nums">{m.val}</div>
              <div className="text-[10px] font-bold text-slate-500 uppercase tracking-tight">{m.sub}</div>
            </div>
          ))}
        </div>

        {/* Calculator Widget & Quick Start */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          
          {/* CALCULATOR (LEFT) */}
          <div className="lg:col-span-7 bg-white rounded-xl border border-slate-200 shadow-sm p-6 space-y-6">
            <div className="flex items-center gap-3 border-b border-slate-100 pb-4">
              <div className="p-2 rounded-lg bg-emerald-50 border border-emerald-100 text-emerald-600">
                <Calculator className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-sm font-black text-slate-900 uppercase tracking-widest">Staking Yield Calculator</h3>
                <p className="text-[10px] text-slate-500 font-bold uppercase">Estimate your passive income in real-time</p>
              </div>
            </div>

            <div className="space-y-4">
              <div className="space-y-2">
                <div className="flex justify-between items-center text-[10px] font-black text-slate-400 uppercase tracking-wider">
                  <span>Delegation Amount (LUM)</span>
                </div>
                <div className="relative">
                  <input
                    type="number"
                    value={stakeAmount}
                    onChange={(e) => setStakeAmount(Math.max(0, parseFloat(e.target.value) || 0))}
                    className="w-full bg-slate-50 border border-slate-200 px-4 py-3 rounded-lg text-sm font-bold focus:outline-none focus:ring-1 focus:ring-emerald-500 focus:bg-white text-slate-800"
                  />
                  <div className="absolute right-4 top-1/2 -translate-y-1/2 text-xs font-black text-slate-400 uppercase tracking-widest select-none">
                    LUM
                  </div>
                </div>
                <input
                  type="range"
                  min="100"
                  max="100000"
                  step="100"
                  value={stakeAmount}
                  onChange={(e) => setStakeAmount(parseInt(e.target.value))}
                  className="w-full h-1 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-emerald-500 mt-2"
                />
                <div className="flex justify-between text-[9px] font-black text-slate-400 uppercase tracking-widest mt-1">
                  <span>Min: 100 LUM</span>
                  <span>Max: 100,000 LUM</span>
                </div>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 border-t border-slate-100 pt-6">
              {[
                { period: "Daily Reward", amt: dailyReward, border: "border-slate-150" },
                { period: "Monthly Reward", amt: monthlyReward, border: "border-slate-150" },
                { period: "Yearly Reward", amt: yearlyReward, border: "border-emerald-200 bg-emerald-50/20" },
              ].map((r, i) => (
                <div key={i} className={cn("p-4 rounded-xl border", r.border)}>
                  <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest block mb-1">{r.period}</span>
                  <div className="text-xl font-black text-slate-800 tabular-nums">
                    +{formatNumber(r.amt, 2)} <span className="text-xs font-bold text-slate-400">LUM</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* QUICK START (RIGHT) */}
          <div className="lg:col-span-5 bg-gradient-to-br from-slate-900 to-[#1e293b] rounded-xl p-6 text-white border border-white/5 flex flex-col justify-between shadow-xl">
            <div className="space-y-4">
              <div className="flex items-center gap-3 border-b border-white/5 pb-4">
                <div className="p-2 rounded-lg bg-white/5 border border-white/10 text-teal-400">
                  <Zap className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-sm font-black text-white uppercase tracking-widest">Staking Quick Start</h3>
                  <p className="text-[10px] text-slate-400 font-bold uppercase">Delegate in 3 simple steps</p>
                </div>
              </div>

              <div className="space-y-4">
                {[
                  { num: "01", title: "Install Lumina Wallet", desc: "Download the Chrome Extension Wallet and create/import your keypair." },
                  { num: "02", title: "Deposit LUM Native Tokens", desc: "Acquire LUM tokens through direct transfers or using the network faucet." },
                  { num: "03", title: "Select Validator & Stake", desc: "Choose a validator from the list below, click Delegate, and sign the txn." },
                ].map((s, idx) => (
                  <div key={idx} className="flex gap-4">
                    <div className="w-8 h-8 rounded-lg bg-teal-500/10 border border-teal-500/20 text-teal-400 flex items-center justify-center shrink-0 font-mono font-black text-sm">
                      {s.num}
                    </div>
                    <div className="space-y-1">
                      <h4 className="text-xs font-black uppercase tracking-wider text-white">{s.title}</h4>
                      <p className="text-[11px] text-slate-400 leading-relaxed font-semibold">{s.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <a 
              href="/lumina-wallet.zip"
              className="mt-6 w-full py-3 bg-teal-500 hover:bg-teal-600 text-slate-950 font-black text-[11px] uppercase tracking-widest rounded-lg transition-colors cursor-pointer text-center block"
            >
              Get Chrome Wallet (Extension)
            </a>
          </div>
        </div>

        {/* Active Validators List from RPC */}
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="px-6 py-4 border-b border-slate-100 bg-slate-50/50 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <ShieldCheck className="w-5 h-5 text-slate-400" />
              <div>
                <h3 className="text-sm font-black text-slate-900 uppercase tracking-widest">Active Validators</h3>
                <p className="text-[10px] text-slate-500 font-bold uppercase">Live data from the RPC node</p>
              </div>
            </div>
          </div>
          
          {loading ? (
            <div className="flex items-center justify-center py-16 gap-3 text-slate-400">
              <Loader2 className="w-5 h-5 animate-spin" />
              <span className="text-sm font-bold">Loading validators from RPC node...</span>
            </div>
          ) : validators.length === 0 ? (
            <div className="flex items-center justify-center py-16 text-slate-400">
              <span className="text-sm font-bold">No active validators found on this node.</span>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left text-[13px]">
                <thead className="bg-slate-50 text-[10px] font-bold text-slate-400 uppercase tracking-widest border-b border-slate-100">
                  <tr>
                    <th className="px-6 py-4">Validator Address</th>
                    <th className="px-6 py-4">Staked Amount</th>
                    <th className="px-6 py-4">Status</th>
                    <th className="px-6 py-4 text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-50">
                  {validators.map((val) => (
                    <tr key={val.address} className="hover:bg-slate-50/50 transition-colors group">
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-3">
                          <div className="w-8 h-8 rounded-lg bg-teal-50 border border-teal-100 text-teal-600 font-black text-xs flex items-center justify-center shrink-0">
                            {val.address.slice(-2).toUpperCase()}
                          </div>
                          <span className="font-bold text-slate-900 font-mono text-[12px] truncate max-w-[280px]">{val.address}</span>
                        </div>
                      </td>
                      <td className="px-6 py-4 font-bold text-slate-700">
                        {formatStake(val.stake)} LUM
                      </td>
                      <td className="px-6 py-4">
                        <span className="inline-flex items-center gap-1.5 text-[9px] font-black px-2.5 py-1 rounded-full uppercase border bg-emerald-50 text-emerald-600 border-emerald-100">
                          <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                          {val.status}
                        </span>
                      </td>
                      <td className="px-6 py-4 text-right">
                        <button
                          onClick={() => handleOpenStaking(val)}
                          className="inline-flex items-center gap-1 bg-teal-600 hover:bg-teal-700 text-white font-black text-[10px] uppercase tracking-widest px-4 py-2 rounded-lg transition-colors cursor-pointer"
                        >
                          Delegate <ArrowUpRight className="w-3.5 h-3.5" />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {/* FAQs Section */}
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 space-y-6">
          <div className="flex items-center gap-3 border-b border-slate-100 pb-4">
            <div className="p-2 rounded-lg bg-slate-50 border border-slate-100 text-slate-600">
              <HelpCircle className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-sm font-black text-slate-900 uppercase tracking-widest">Frequently Asked Questions</h3>
              <p className="text-[10px] text-slate-500 font-bold uppercase">Learn more about consensus, delegation fees, and safety parameters</p>
            </div>
          </div>

          <div className="divide-y divide-slate-100">
            {FAQS.map((faq, i) => {
              const isOpen = openFaq === i
              return (
                <div key={i} className="py-4 first:pt-0 last:pb-0">
                  <button
                    onClick={() => setOpenFaq(isOpen ? null : i)}
                    className="w-full flex items-center justify-between text-left focus:outline-none group"
                  >
                    <span className="text-[13px] font-bold text-slate-900 group-hover:text-teal-600 transition-colors">
                      {faq.q}
                    </span>
                    <ChevronDown className={cn(
                      "w-4 h-4 text-slate-400 transition-transform duration-200 group-hover:text-slate-600",
                      isOpen ? "rotate-180" : ""
                    )} />
                  </button>
                  {isOpen && (
                    <div className="mt-2 text-xs text-slate-500 font-medium leading-relaxed animate-in slide-in-from-top-1 duration-150">
                      {faq.a}
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        </div>
      </main>

      {/* Staking Guide Modal */}
      {showStakingModal && selectedVal && (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4 backdrop-blur-sm animate-in fade-in duration-200">
          <div 
            onClick={() => setShowStakingModal(false)}
            className="absolute inset-0 cursor-default" 
          />
          
          <div className="w-full max-w-xl bg-white rounded-2xl relative z-10 shadow-2xl overflow-hidden flex flex-col animate-in scale-in duration-200">
            <div className="bg-[#111827] text-white p-6 relative overflow-hidden">
              <div className="absolute -right-12 -top-12 w-32 h-32 bg-teal-500/10 rounded-full blur-3xl" />
              
              <div className="flex justify-between items-center relative z-10">
                <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[9px] font-black uppercase tracking-widest bg-teal-950/40 border border-teal-500/30 text-teal-400">
                  Delegation Setup
                </span>
                <button
                  onClick={() => setShowStakingModal(false)}
                  className="p-1 rounded-full bg-white/5 hover:bg-white/10 text-slate-400 hover:text-white transition-colors"
                >
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>

              <h3 className="text-lg font-black uppercase italic tracking-tight mt-3">
                Delegate To Validator
              </h3>
              <span className="text-[11px] text-teal-400 font-mono font-bold block mt-1 break-all">
                {selectedVal.address}
              </span>
            </div>

            <div className="p-6 space-y-6 max-h-[70vh] overflow-y-auto custom-scrollbar">
              <div className="bg-slate-50 border border-slate-200 rounded-xl p-5 space-y-3">
                <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest block">Option 1: Chrome Extension Wallet (Recommended)</span>
                <p className="text-xs text-slate-500 font-semibold leading-relaxed">
                  The easiest way to delegate is using the Lumina Wallet Chrome Extension. Open your extension, navigate to the Staking section, and enter the amount you wish to delegate.
                </p>
                <a 
                  href="/lumina-wallet.zip"
                  className="inline-flex items-center gap-1.5 bg-teal-600 hover:bg-teal-700 text-white font-black text-[10px] uppercase tracking-widest px-4 py-2 rounded-lg transition-colors cursor-pointer"
                >
                  Download Wallet <ArrowUpRight className="w-3.5 h-3.5" />
                </a>
              </div>

              <div className="space-y-3">
                <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest block">Option 2: CLI Staking Command</span>
                
                <div className="bg-slate-900 rounded-xl border border-white/5 p-4 space-y-2.5 relative font-mono text-[11px] text-teal-400 font-bold overflow-hidden shadow-inner">
                  <div className="flex justify-between items-center text-[9px] font-black uppercase text-slate-500 tracking-wider">
                    <span>Shell Script</span>
                    <button
                      onClick={() => handleCopy(`lumina-cli stake --amount ${stakeAmount} --validator ${selectedVal.address} --keypair my_key.json`, "cli-script")}
                      className="text-slate-400 hover:text-white transition-colors cursor-pointer"
                    >
                      {copiedId === "cli-script" ? (
                        <span className="text-emerald-400 flex items-center gap-1">Copied! <CheckCircle2 className="w-3 h-3" /></span>
                      ) : (
                        <span className="flex items-center gap-1">Copy <Copy className="w-3 h-3" /></span>
                      )}
                    </button>
                  </div>
                  <pre className="whitespace-pre-wrap break-all leading-normal select-all">
                    lumina-cli stake --amount {stakeAmount} --validator {selectedVal.address} --keypair my_key.json
                  </pre>
                </div>
              </div>
            </div>

            <div className="p-4 border-t border-slate-100 bg-slate-50 flex items-center justify-end gap-3 shrink-0">
              <button
                onClick={() => setShowStakingModal(false)}
                className="px-4 py-2 border border-slate-200 hover:bg-slate-100 text-[10px] text-slate-600 font-black uppercase tracking-wider rounded-lg transition-colors cursor-pointer"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      <Footer />
    </div>
  )
}
